# fly.toml app configuration file generated for authenticator-service-daniel on 2025-10-18T17:17:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'authenticator-service-daniel'
primary_region = 'jnb'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 0.0.0.0:8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
