name: CI → Fly

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly (remote-only)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ~/.fly/bin/flyctl deploy --remote-only --app authenticator-service-daniel
